package io.github.eealba.payper.orders.v2.model;


import io.github.eealba.jasoner.JasonerSingleVO;

/**
 * The unique ID for a customer generated by PayPal.
 */
@JasonerSingleVO
public record MerchantPartnerCustomerId(String value) {

    public MerchantPartnerCustomerId(String value) {
        if (value == null) {
            throw new IllegalArgumentException("Field value can`t be null");
        }
        if (!value.matches("^[0-9a-zA-Z_-]+$")) {
            throw new IllegalArgumentException("The value: " + value + " does not match the required pattern");
        }
        this.value = value;
    }

}
