package io.github.eealba.payper.orders.v2.model;



/**
 * The unique ID for a customer generated by PayPal.
 */
public record MerchantPartnerCustomerId(String value) {

    public MerchantPartnerCustomerId(String value) {
        if (value == null) {
            throw new IllegalArgumentException("Field value can`t be null");
        }
        if (!value.matches("^[0-9a-zA-Z_-]+$")) {
            throw new IllegalArgumentException("Invalid pattern for field value");
        }
        this.value = value;
    }

}
