package io.github.eealba.payper.webhooks.v1.api;

import io.github.eealba.payper.core.client.RequestSpec;
import io.github.eealba.payper.webhooks.v1.model.Error;
import io.github.eealba.payper.webhooks.v1.model.VerifyWebhookSignature;
import io.github.eealba.payper.webhooks.v1.model.VerifyWebhookSignatureResponse;

/**
 * API to verify the signature of a webhook.
 * <p>
 *     This API is used to verify the signature of a webhook. The signature is generated by the webhook
 *
 * @since 1.0
 * @version 1.0
 * @author Edgar Alba
 */
public interface VerifyWebhookSignatureApi extends RequestSpec<VerifyWebhookSignatureResponse, Error>,
        RequestSpec.BodySpec<VerifyWebhookSignatureApi, VerifyWebhookSignature> {
}
